### PR TITLE
use host if there is no domain to identify referer

### PR DESCRIPTION
**Pull request by lengshuiyulangcn**
If the server don't have a domain, the following method will throw an error. so use host if there is no domain.

### CODE REVIEW

**Comment by songjiayang** [comment]
Hi @lengshuiyulangcn
Thank your PR first. There are some conflicts with your PR and i think the latest code has fixed it,  you can check it [here](https://github.com/ruby-china/ruby-china/blob/983e944af849448c6f17d6eff022e699249c5336/app/controllers/sessions_controller.rb#L34) if not fix conflict and PR again.

**Comment by lengshuiyulangcn** [comment]
Hi @songjiayang 

I have fixed conflict and my fix is due to another reason(if a domain does not exists). plz have a check, thank you.

**Comment by huacnlee** [comment]
> If the server don't have a domain

127.0.0.1 这种情况？

**Comment by lengshuiyulangcn** [comment]
@huacnlee 也包括这种情况。
之前部署到remote server上，暂时没绑定domain，用ip访问的时候就出现了问题。

**Pull request merged**
